In [1]:
import random
import numpy as np
import os
import torch
from torch.utils.data import Dataset, DataLoader, TensorDataset
from torch.autograd import Variable
#from sklearn.model_selection import train_test_split
import torchvision
import torchvision.transforms as transforms

from PIL import Image
import cv2
import matplotlib.pyplot as plt
import glob
import matplotlib.pyplot as plt

In [2]:
import sys, os
sys.path.append("..")
from dataloader import Dataload
from utils.plot import plot_rect

In [3]:
batch_size = 1
train_dataloader = Dataload(r"H:\DATASET\CLASSDATA\training_set\train",same_matrix=True)
train_loader= DataLoader(
    dataset = train_dataloader,
    batch_size = batch_size,
    shuffle = True,
    drop_last = True
)


total: 537


In [9]:
train_dataloader = Dataload(r"H:\DATASET\CLASSDATA\test_images",same_matrix=True, data_type='test')
train_loader= DataLoader(
    dataset = train_dataloader,
    batch_size = batch_size,
    shuffle = True,
    drop_last = True
)


total: 430


In [4]:
image, d = train_dataloader[429]

In [5]:
image.shape

torch.Size([3, 128, 128])

In [8]:
d[:,1:]

tensor([[0.6405, 0.7714, 0.0514, 0.0371],
        [0.0000, 0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000, 0

In [7]:
d

tensor([[3.0000, 0.6405, 0.7714, 0.0514, 0.0371],
        [8.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [8.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [8.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [8.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [8.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [8.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [8.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [8.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [8.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [8.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [8.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [8.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [8.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [8.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [8.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [8.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [8.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [8.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [8.0000, 0.0000, 0.0000, 0.0000, 0.0000],


In [6]:
train_dataloader[0]

发现异常
RuntimeError
image can 't read:H:\DATASET\CLASSDATA\test_images\images\0.png


In [21]:
count = 0
for i in train_loader:
    count += 1
    a,b = i
    print(count)

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99
100
101
102
103
104
105
106
107
108
109
110
111
112
113
114
115
116
117
118
119
120
121
122
123
124
125
126
127
128
129
130
131
132
133
134
135
136
137
138
139
140
141
142
143
144
145
146
147
148
149
150
151
152
153
154
155
156
157
158
159
160
161
162
163
164
165
166
167
168
169
170
171
172
173
174
175
176
177
178
179
180
181
182
183
184
185
186
187
188
189
190
191
192
193
194
195
196
197
198
199
200
201
202
203
204
205
206
207
208
209
210
211
212
213
214
215
216
217
218
219
220
221
222
223
224
225
226
227
228
229
230
231
232
233
234
235
236
237
238
239
240
241
242
243
244
245
246
247
248
249
250
251
252
253
254
255
256
257
258
259
260
261
262
263
264
265
266
267
268
269
270
271
272
273
274
275
276
277


In [22]:
a,b

(tensor([[[[0.5666, 0.5825, 0.5825,  ..., 0.5666, 0.5666, 0.5825],
           [0.5825, 0.5984, 0.5984,  ..., 0.5666, 0.5666, 0.5666],
           [0.5825, 0.5984, 0.5984,  ..., 0.5666, 0.5666, 0.5666],
           ...,
           [0.5984, 0.5984, 0.5984,  ..., 0.5666, 0.5666, 0.5825],
           [0.5984, 0.5984, 0.5825,  ..., 0.5825, 0.5825, 0.5825],
           [0.5984, 0.5984, 0.5825,  ..., 0.5666, 0.5666, 0.5825]],
 
          [[0.6289, 0.6289, 0.6289,  ..., 0.6289, 0.6289, 0.6289],
           [0.6289, 0.6450, 0.6450,  ..., 0.6289, 0.6289, 0.6289],
           [0.6450, 0.6450, 0.6450,  ..., 0.6289, 0.6289, 0.6289],
           ...,
           [0.6611, 0.6450, 0.6450,  ..., 0.6450, 0.6450, 0.6450],
           [0.6450, 0.6450, 0.6450,  ..., 0.6289, 0.6450, 0.6450],
           [0.6450, 0.6450, 0.6450,  ..., 0.6289, 0.6450, 0.6450]],
 
          [[0.7066, 0.7066, 0.7066,  ..., 0.7216, 0.7216, 0.7216],
           [0.7066, 0.7216, 0.7216,  ..., 0.7216, 0.7216, 0.7216],
           [0.7216, 0.72

In [ ]:
x = [float(i) for i in range(8)]
y= [False for i in range(8)]
pos = []
i =-1
for data in train_loader:
    i +=1
    img,label = data
    # print(label[0][0])
    if(label[0][0] in x and y[int(label[0][0])] == False ):
        pos.append(i)
        y[int(label[0][0])] =True
        print(label[0][0])
        # plt.imshow(num_img)

In [ ]:
pos

In [ ]:
photo = []
photo_label = []
for i in pos:
    num_img, label = train_dataloader[i]
    num_img = np.array(num_img[0,:,:])
    photo.append(num_img)
    photo_label.append(label)
plt.figure(figsize=(12,16))
for i in range(len(pos)):
    plot_rect(photo[i], photo_label[i])

In [ ]:
photo = []
photo_label = []
for i in pos:
    num_img, label = train_dataloader[i]
    num_img = np.array(num_img)
    num_img = num_img.swapaxes(0, 1)
    num_img = num_img.swapaxes(1, 2)
    photo.append(num_img)
    photo_label.append(label)
plt.figure(figsize=(12,16))
for i in range(len(pos)):
    plot_rect(photo[i], photo_label[i])


In [ ]:
photo_label[-1]

In [ ]:
for coord in photo_label[-1]:
    print(coord)

In [ ]:
plt.imshow(img)
index = 0
for data in new_list_1:
    index += 1
    plt.scatter(x=data['x_'],y=data['y_'],s = 1)
    plt.text(data['x_'], data['y_'], '{:0.0f}'.format(index), ha='center', va='center')
plt.show()
plt.gca().add_patch(plt.Rectangle(xy=(cat_dict['bbox'][i][1], cat_dict['bbox'][i][0]),
                                  width=cat_dict['bbox'][i][3] - cat_dict['bbox'][i][1], 
                                  height=cat_dict['bbox'][i][2] - cat_dict['bbox'][i][0],
                                  edgecolor=[c / 255 for c in label_colors[cat_idx]],
                                  fill=False, linewidth=2))

In [ ]:
def plot_rect(image, label):
    plt.figure(figsize=(8,8))
    plt.imshow(image)
    if(len(image.shape) == 3):
        
        width,height,channel = image.shape
    else:
        width,height = image.shape
    for coord in label:
        class_number, x,y,w,h= coord 
        centerx = width*(x - w/2)
        centery = height*(y - h/2)
        W = w * width
        H = h * height
        plt.gca().add_patch(
            plt.Rectangle(
                xy=(centerx,centery),
                width=W, 
                height=H,
                edgecolor='red',
                fill=False, linewidth=1
            )
        )
        plt.text(centerx, centery, '{}'.format(int(class_number)), ha='center', va='center')
    return 

In [ ]:
plot_rect(photo[-1][:,:,0], photo_label[-1])

In [ ]:
plt.figure(figsize=(8,8))
plt.imshow(photo[-1][:,:,0])
width,height = photo[-1][:,:,0].shape
for coord in photo_label[-1]:
    class_number, x,y,w,h= coord 
    centerx = width*((1-x) - w/2)
    centery = height*(y - h/2)
    W = w * width
    H = h * height
    plt.gca().add_patch(
        plt.Rectangle(
            xy=(centerx,centery),
            width=W, 
            height=H,
            edgecolor='red',
            fill=False, linewidth=1
        )
    )
    plt.text(centerx, centery, '{}'.format(int(class_number)), ha='center', va='center')

In [ ]:
import os
import glob
file_path =r'E:\Dataset\training_set\train\labels'
file = glob.glob(file_path+'/*.txt')
# print(file)
maxNum = 0

for i in file:
    label = []
    with open(i) as f:
        lines = f.readlines()
        for line in lines:
            x = line.replace('\n', '').split(' ')
            x = [float(i) for i in x]
            label.append(x)
    if(len(label)>maxNum):
        maxNum = len(label)
        print(i)